### ISSUE TITLE
[Feature Request] optionally mute

### ISSUE THREAD

**Issue by lukecfairchild** [norihiro/obs-mute-filter#4]
I have been trying to find a filter that can mute, but can be triggered specifically by the user muting it on the dashboard. Reason being is I am hoping for a way to dynamically mute an NDI filter. Is that something that could be possible with this with some changes?

**Comment by norihiro** [comment]
Can my PR #3 be your solution?
I'm adding a new filter `Discard Audio by UI`, which will discard (same as the current Mute Filter) only while user has muted the attached audio source by the Mixer dock.
You can download a preliminary version from the PR page and navigating 'show all checks' -> 'Details' at the right of 'Plugin Build / windows_build' -> 'Summary' -> 'artifact-windows-obs27-x64'. Direct link is [artifact-windows-obs27-x64](https://github.com/norihiro/obs-mute-filter/actions/runs/8876153043/artifacts/1456021384).

**Comment by lukecfairchild** [comment]
Just tested it, that works wonderfully!!

**Comment by norihiro** [comment]
Thank you. I will test it on my side at the next Sunday and will make a release.

**Comment by norihiro** [comment]
[The version 0.3.0](https://github.com/norihiro/obs-mute-filter/releases/tag/0.3.0) was released just now.
